# Generated by Django 3.0 on 2022-04-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
